/**
 * ClientPortalPreview — "Your clients will love you."
 * Shows a beautiful, simplified client portal UI mockup with
 * Framer Motion entrance animation on scroll.
 */
'use client'

import { motion } from 'framer-motion'
import { CheckCircle, Upload, FileImage, FileText, Zap } from 'lucide-react'

type PortalItem = { type: 'image' | 'text'; label: string; done: boolean }

const PORTAL_ITEMS: PortalItem[] = [
  { type: 'image', label: 'Logo Files (SVG/PNG)', done: true },
  { type: 'image', label: 'Brand Color Guide',    done: true },
  { type: 'text',  label: 'Website Copy Deck',    done: false },
  { type: 'text',  label: 'Contract (PDF)',        done: false },
]

export default function ClientPortalPreview() {
  return (
    <section className="max-w-5xl mx-auto px-4 sm:px-6 py-16 md:py-28 border-t-[3px] border-dashed border-muted">

      {/* Heading */}
      <motion.div
        initial={{ opacity: 0, y: 24 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: '-80px' }}
        transition={{ duration: 0.5, ease: 'easeOut' as const }}
        className="text-center mb-10 md:mb-16"
      >
        <span className="tag-label">Client experience</span>
        <h2 className="font-heading text-3xl sm:text-5xl md:text-6xl text-ink mt-4 leading-tight">
          Your clients will love&nbsp;you.
        </h2>
        <p className="font-body text-xl text-ink/55 mt-4 max-w-lg mx-auto">
          No Signup Required.{' '}
          <strong className="text-ink">Just Drag, Drop, and Done.</strong>
        </p>
      </motion.div>

      {/* Two-column: caption + portal mockup */}
      <div className="grid md:grid-cols-2 gap-8 md:gap-14 items-center">

        {/* Left: benefit bullets */}
        <motion.div
          initial={{ opacity: 0, x: -30 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true, margin: '-60px' }}
          transition={{ duration: 0.55, ease: 'easeOut' as const }}
          className="flex flex-col gap-6"
        >
          {[
            {
              icon: '🔗',
              title: 'One link, no account',
              desc: 'Clients open their unique portal in any browser. No sign-up, no app download, no password reset hell.',
            },
            {
              icon: '📋',
              title: 'They know exactly what to send',
              desc: 'Each asset request shows the file type, size limit, and custom instructions generated by AI.',
            },
            {
              icon: '✅',
              title: "AI confirms it's right",
              desc: "Llama 3.3 validates every upload instantly — resolution, format, completeness — before it hits your dashboard.",
            },
            {
              icon: '🏷️',
              title: 'Files arrive already named',
              desc: 'Smart renaming renames every file to your convention: ClientSlug_Asset_Project_Date. Zero manual sorting.',
            },
          ].map((item, i) => (
            <motion.div
              key={item.title}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1, ease: 'easeOut' as const }}
              className="flex items-start gap-4"
            >
              <span
                className="text-2xl flex-shrink-0 w-11 h-11 bg-muted border-2 border-ink/15 flex items-center justify-center"
                style={{ borderRadius: '50% 45% 55% 48% / 50% 52% 48% 50%', fontSize: '1.25rem' }}
              >
                {item.icon}
              </span>
              <div>
                <h4 className="font-heading text-lg text-ink">{item.title}</h4>
                <p className="font-body text-sm text-ink/60 mt-0.5 leading-relaxed">{item.desc}</p>
              </div>
            </motion.div>
          ))}
        </motion.div>

        {/* Right: portal mockup card */}
        <motion.div
          initial={{ opacity: 0, x: 30 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true, margin: '-60px' }}
          transition={{ duration: 0.6, ease: 'easeOut' as const }}
          className="relative"
        >
          {/* Browser chrome */}
          <div
            className="border-[3px] border-ink overflow-hidden bg-paper"
            style={{
              borderRadius: '20px 20px 16px 16px / 20px 20px 16px 16px',
              boxShadow: '6px 6px 0px 0px #2d2d2d',
            }}
          >
            {/* Browser bar */}
            <div className="bg-ink/90 px-4 py-2.5 flex items-center gap-2.5">
              <div className="flex gap-1.5">
                {['bg-red-400', 'bg-yellow-400', 'bg-green-400'].map(c => (
                  <div key={c} className={`w-2.5 h-2.5 rounded-full ${c} opacity-80`} />
                ))}
              </div>
              <div
                className="flex-1 bg-white/15 text-white/60 font-body text-xs px-3 py-1 truncate text-center"
                style={{ borderRadius: '20px' }}
              >
                fetchasset.com/portal/acme-corp-✨-abc123
              </div>
            </div>

            {/* Portal content */}
            <div className="p-5 flex flex-col gap-4">

              {/* Header */}
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-heading text-xl text-ink">Acme Corp — Brand Identity</p>
                  <p className="font-body text-xs text-ink/45 mt-0.5">Deadline: Wednesday, 25 February</p>
                </div>
                <div
                  className="font-body text-xs bg-[#fffde7] border-2 border-ink/20 px-2 py-1 text-ink/60"
                  style={{ borderRadius: '20px 5px 20px 5px / 5px 20px 5px 20px' }}
                >
                  2 of 4 done
                </div>
              </div>

              {/* Progress bar */}
              <div
                className="w-full h-2.5 bg-muted border-2 border-ink/20 overflow-hidden"
                style={{ borderRadius: '255px 15px 225px 15px / 15px 225px 15px 255px' }}
              >
                <motion.div
                  initial={{ width: 0 }}
                  whileInView={{ width: '50%' }}
                  viewport={{ once: true }}
                  transition={{ duration: 1.2, ease: 'easeOut' as const, delay: 0.6 }}
                  className="h-full bg-ink"
                  style={{ borderRadius: '255px 15px 225px 15px / 15px 225px 15px 255px' }}
                />
              </div>

              {/* Asset list */}
              <div className="flex flex-col gap-2.5">
                {PORTAL_ITEMS.map((item, i) => (
                  <motion.div
                    key={item.label}
                    initial={{ opacity: 0, x: -10 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: 0.3 + i * 0.1, ease: 'easeOut' as const }}
                    className="flex items-center gap-3 p-2.5 border-2 border-ink/10 bg-white/40"
                    style={{ borderRadius: '12px 3px 12px 3px / 3px 12px 3px 12px' }}
                  >
                    <div
                      className={`w-7 h-7 flex items-center justify-center flex-shrink-0 ${item.done ? 'text-green-600 bg-green-50' : 'text-ink/40 bg-muted'}`}
                      style={{ borderRadius: '50%' }}
                    >
                      {item.done ? (
                        <CheckCircle size={15} className="text-green-600" strokeWidth={2.5} />
                      ) : item.type === 'image' ? (
                        <FileImage size={15} strokeWidth={2} />
                      ) : (
                        <FileText size={15} strokeWidth={2} />
                      )}
                    </div>
                    <span className={`font-body text-sm flex-1 ${item.done ? 'line-through text-ink/45' : 'text-ink'}`}>
                      {item.label}
                    </span>
                    {!item.done && (
                      <span
                        className="font-body text-xs bg-muted text-ink/50 px-2 py-0.5"
                        style={{ borderRadius: '20px' }}
                      >
                        Upload
                      </span>
                    )}
                  </motion.div>
                ))}
              </div>

              {/* Drop zone */}
              <motion.div
                animate={{ borderColor: ['rgba(45,45,45,0.2)', 'rgba(45,45,45,0.5)', 'rgba(45,45,45,0.2)'] }}
                transition={{ duration: 2.8, repeat: Infinity, ease: 'easeInOut' as const }}
                className="border-[3px] border-dashed p-6 flex flex-col items-center gap-2 bg-muted/30"
                style={{ borderRadius: '180px 45px 200px 35px / 40px 190px 30px 170px' }}
              >
                <Upload className="w-7 h-7 text-ink/30" />
                <p className="font-body text-xs text-ink/40 text-center">Drop files here or click to browse</p>
              </motion.div>
            </div>
          </div>

          {/* AI badge floating */}
          <motion.div
            initial={{ opacity: 0, scale: 0.7, rotate: -4 }}
            whileInView={{ opacity: 1, scale: 1, rotate: -4 }}
            viewport={{ once: true }}
            transition={{ delay: 0.8, type: 'spring', stiffness: 200 }}
            className="absolute -bottom-5 -left-5 bg-ink text-paper px-3 py-1.5 font-body text-xs font-bold"
            style={{
              borderRadius: '255px 15px 225px 15px / 15px 225px 15px 255px',
              boxShadow: '3px 3px 0px 0px #22c55e',
              transform: 'rotate(-4deg)',
            }}
          >
            <Zap size={12} className="inline mr-1" fill="currentColor" />
            AI validates on drop
          </motion.div>

          {/* No login badge */}
          <motion.div
            initial={{ opacity: 0, scale: 0.7, rotate: 3 }}
            whileInView={{ opacity: 1, scale: 1, rotate: 3 }}
            viewport={{ once: true }}
            transition={{ delay: 1.0, type: 'spring', stiffness: 200 }}
            className="absolute -top-5 -right-3 bg-[#fffde7] border-[3px] border-ink text-ink px-3 py-1.5 font-body text-xs font-bold"
            style={{
              borderRadius: '245px 18px 200px 20px / 22px 210px 14px 240px',
              boxShadow: '3px 3px 0px 0px #2d2d2d',
              transform: 'rotate(3deg)',
            }}
          >
            No login needed 🪄
          </motion.div>
        </motion.div>
      </div>
    </section>
  )
}
